package cn.cofco.cpmp.wsclient.splrfbk;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-13T23:31:04.561+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.cofco.com/segment/customer_supplier", name = "SI_CUSSUPPLIER_STATUS_OUT")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICUSSUPPLIERSTATUSOUT {

    @WebMethod(operationName = "SI_CUSSUPPLIER_STATUS_OUT", action = "http://sap.com/xi/WebService/soap1.1")
    @Oneway
    public void siCUSSUPPLIERSTATUSOUT(
        @WebParam(partName = "MT_CUSSUPPLIER_STATUS", name = "MT_CUSSUPPLIER_STATUS", targetNamespace = "http://www.cofco.com/segment/customer_supplier")
        DTCUSSUPPLIERSTATUS mtCUSSUPPLIERSTATUS
    );
}
