package cn.cofco.cpmp.wsclient.splrfbk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-13T23:31:04.586+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "SI_CUSSUPPLIER_STATUS_OUTService", 
                  wsdlLocation = "classpath:wsdl/splrfbk.wsdl",
                  targetNamespace = "http://www.cofco.com/segment/customer_supplier") 
public class SICUSSUPPLIERSTATUSOUTService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cofco.com/segment/customer_supplier", "SI_CUSSUPPLIER_STATUS_OUTService");
    public final static QName HTTPSPort = new QName("http://www.cofco.com/segment/customer_supplier", "HTTPS_Port");
    public final static QName HTTPPort = new QName("http://www.cofco.com/segment/customer_supplier", "HTTP_Port");
    static {
        URL url = null;
        try {
            url = new URL("classpath:wsdl/splrfbk.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SICUSSUPPLIERSTATUSOUTService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/splrfbk.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SICUSSUPPLIERSTATUSOUTService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SICUSSUPPLIERSTATUSOUTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SICUSSUPPLIERSTATUSOUTService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SICUSSUPPLIERSTATUSOUTService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SICUSSUPPLIERSTATUSOUTService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SICUSSUPPLIERSTATUSOUTService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SICUSSUPPLIERSTATUSOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICUSSUPPLIERSTATUSOUT getHTTPSPort() {
        return super.getPort(HTTPSPort, SICUSSUPPLIERSTATUSOUT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICUSSUPPLIERSTATUSOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SICUSSUPPLIERSTATUSOUT getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SICUSSUPPLIERSTATUSOUT.class, features);
    }


    /**
     *
     * @return
     *     returns SICUSSUPPLIERSTATUSOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICUSSUPPLIERSTATUSOUT getHTTPPort() {
        return super.getPort(HTTPPort, SICUSSUPPLIERSTATUSOUT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICUSSUPPLIERSTATUSOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SICUSSUPPLIERSTATUSOUT getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SICUSSUPPLIERSTATUSOUT.class, features);
    }

}
