package cn.cofco.cpmp.wsclient.bpm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-10-01T15:49:37.266+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://cofco.com/lyt/bpm", name = "SI_LYT2BPM_APPRV_OUT")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SILYT2BPMAPPRVOUT {

    @WebMethod(operationName = "SI_LYT2BPM_APPRV_OUT", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "launchFormCollaboration4sapResponse", targetNamespace = "http://impl.flow.services.v3x.seeyon.com", partName = "parameters")
    public LaunchFormCollaboration4SapResponse siLYT2BPMAPPRVOUT(
            @WebParam(partName = "parameters", name = "launchFormCollaboration4sap", targetNamespace = "http://impl.flow.services.v3x.seeyon.com")
                    LaunchFormCollaboration4Sap parameters
    );
}
