package cn.cofco.cpmp.wsclient.splr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-08-30T22:13:30.933+08:00
 * Generated source version: 3.1.11
 *
 */
@WebService(targetNamespace = "http://www.cofco.com/bpm/customer_supplier", name = "SI_CUSSUPPLIER_ACCESS_OUT")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICUSSUPPLIERACCESSOUT {

    @WebMethod(operationName = "CusSupplier_Apply", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "setPartnerResponse", targetNamespace = "http://ibm.com/service/partner/", partName = "setPartnerResponse")
    public SetPartnerResponse cusSupplierApply(
            @WebParam(partName = "parameters", name = "setPartner", targetNamespace = "http://ibm.com/service/partner/")
                    SetPartner parameters
    );

    @WebMethod(operationName = "CusSupplier_Query", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "getPartnerResponse", targetNamespace = "http://ibm.com/service/partner/", partName = "getPartnerResponse")
    public GetPartnerResponse cusSupplierQuery(
            @WebParam(partName = "parameters", name = "getPartner", targetNamespace = "http://ibm.com/service/partner/")
                    GetPartner parameters
    );
}
