package cn.cofco.cpmp.wsclient.matfbk;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-15T13:13:24.221+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.cofco.com/segment/material", name = "SI_MaterialStatus_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIMaterialStatusOut {

    @WebMethod(operationName = "SI_MaterialStatus_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @Oneway
    public void siMaterialStatusOut(
        @WebParam(partName = "MT_MaterialStatus", name = "MT_MaterialStatus", targetNamespace = "http://www.cofco.com/segment/material")
        DTMaterialStatus mtMaterialStatus
    );
}
